apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  labels:
    app.kubernetes.io/name: {{ .Values.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.name }}
      annotations:
        kubectl.kubernetes.io/default-container: round-table
    spec:
      containers:
        - name: round-table
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: REDIS_HOST
              value: {{ .Values.redis.fullnameOverride }}
            {{- if eq .Values.network "preview" }}
            - name: NEXT_PUBLIC_NETWORK
              value: {{ .Values.network }}
            {{- end }}
            - name: NEXT_PUBLIC_GRAPHQL
              value: {{ .Values.options.gqlUri }}
            - name: NEXT_PUBLIC_SUBMIT
              value: {{ .Values.options.submitUri }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
