apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: round-table
  namespace: argocd
  labels:
    app.kubernetes.io/name: round-table
spec:
  goTemplate: true
  goTemplateOptions:
    - missingkey=error
  generators:
    - clusters:
        selector:
          matchLabels:
            liqwid.finance/flagship-cluster-type: sailor
            liqwid.finance/flagship-env: dev
        values:
          network: preview
    - clusters:
        selector:
          matchLabels:
            liqwid.finance/flagship-cluster-type: sailor
            liqwid.finance/flagship-env: dev
        values:
          network: mainnet
  template:
    metadata:
      name: round-table-{{ .name }}-{{ .values.network }}
      labels:
        app.kubernetes.io/name: liqwid-api
    spec:
      project: tools
      destination:
        name: "{{ .name }}"
        namespace: tools
      source:
        repoURL: https://github.com/Liqwid-Labs/round-table
        targetRevision: HEAD
        path: ci/chart
        helm:
          parameters:
            - name: network
              value: "{{ .values.network }}"
            - name: name
              value: "{{ .values.network }}-round-table"
            - name: redis.fullnameOverride
              value: "{{ .values.network }}-round-table-redis"
            - name: image.tag
              value: $ARGOCD_APP_REVISION
      syncPolicy:
        automated: {}
