name: Deploy
on:
  push:
    branches:
      - main

concurrency: deploy

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        uses: docker/build-push-action@v5
        with:
          push: true
          secrets: NPM_TOKEN=${{ github.token }}
          tags: |
            ghcr.io/liqwid-labs/round-table:${{ github.sha }}
            ghcr.io/liqwid-labs/round-table:latest

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Authenticate Flagship
        uses: liqwid-labs/flagship-authenticate-action@main
        with:
          kubeconfig: ${{ secrets.ARGOCD_DEV_KUBECONFIG }}

      - name: Deploy ArgoCD Application
        run: kubectl apply -f ci/app.yaml
